import os

# OpenAI Configuration
OPENAI_API_KEY = "your-openai-api-key"

# Interview Categories and Questions
INTERVIEW_QUESTIONS = {
    "Technical": [
        "Describe a complex technical problem you solved and your approach to it.",
        "How do you ensure code quality and maintainability in your projects?",
        "Explain a technical concept to a non-technical person.",
        "What's your experience with cloud technologies and which ones do you prefer?",
        "How do you approach debugging complex issues?",
        "Describe your experience with database design and optimization.",
        "What's your approach to learning new programming languages or frameworks?",
        "How do you handle technical disagreements with team members?",
        "Describe a time when you had to optimize for performance.",
        "What's your experience with testing methodologies?",
        "How do you stay updated with the latest technology trends?",
        "Describe your experience with API design and development.",
        "What's your approach to system architecture?",
        "How do you handle technical debt in projects?",
        "Describe a challenging technical project you led.",
        "What's your experience with DevOps practices?",
        "How do you approach security in software development?",
        "Describe your experience with microservices architecture.",
        "What's your approach to scaling applications?",
        "How do you handle legacy code refactoring?"
    ],
    "Behavioral": [
        "Tell me about a time when you had to work with a difficult team member.",
        "Describe a situation where you had to adapt to significant changes.",
        "How do you handle stress and pressure in the workplace?",
        "Tell me about a time you failed and what you learned from it.",
        "Describe a situation where you took initiative.",
        "How do you prioritize tasks when everything seems urgent?",
        "Tell me about a time you had to deliver bad news.",
        "Describe how you've handled a conflict with a coworker.",
        "Tell me about a time you had to learn something quickly.",
        "How do you handle constructive criticism?",
        "Describe a time you had to motivate others.",
        "Tell me about a time you had to make a difficult decision.",
        "How do you build relationships with colleagues?",
        "Describe a time you had to persuade someone.",
        "Tell me about a time you had to work under tight deadlines.",
        "How do you handle work-life balance?",
        "Describe a time you had to deal with ambiguity.",
        "Tell me about a time you had to lead without authority.",
        "How do you approach giving feedback to others?",
        "Describe a time you had to handle a crisis."
    ],
    "Management": [
        "Describe your leadership style and how you adapt it.",
        "How do you motivate underperforming team members?",
        "Tell me about a time you had to let someone go.",
        "How do you handle conflicts within your team?",
        "Describe your approach to team building.",
        "How do you delegate tasks effectively?",
        "Tell me about a time you had to make an unpopular decision.",
        "How do you measure team performance?",
        "Describe your approach to professional development for your team.",
        "How do you handle budget constraints?",
        "Tell me about a time you had to lead through change.",
        "How do you ensure your team meets deadlines?",
        "Describe your approach to strategic planning.",
        "How do you handle competing priorities from stakeholders?",
        "Tell me about a time you had to scale a team.",
        "How do you foster innovation in your team?",
        "Describe your approach to risk management.",
        "How do you communicate with executive leadership?",
        "Tell me about a time you had to turn around a failing project.",
        "How do you ensure alignment across multiple teams?"
    ],
    "Sales & Marketing": [
        "Describe your approach to building a sales pipeline.",
        "How do you handle objections from potential clients?",
        "Tell me about your most successful sale.",
        "How do you qualify leads effectively?",
        "Describe your experience with CRM systems.",
        "How do you build long-term relationships with clients?",
        "Tell me about a time you lost a deal and what you learned.",
        "How do you approach market research and analysis?",
        "Describe your experience with digital marketing strategies.",
        "How do you measure marketing campaign success?",
        "Tell me about a time you had to negotiate a complex deal.",
        "How do you stay motivated during sales slumps?",
        "Describe your approach to customer segmentation.",
        "How do you collaborate with other departments?",
        "Tell me about a time you had to pivot your strategy.",
        "How do you handle competitive markets?",
        "Describe your experience with content marketing.",
        "How do you approach brand positioning?",
        "Tell me about a time you exceeded sales targets.",
        "How do you use data to drive sales decisions?"
    ]
}